# Generated by Django 2.2 on 2020-03-11 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('uid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
                ('original_publisher', models.CharField(max_length=200)),
                ('digital_publisher', models.CharField(max_length=200)),
                ('item_format', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('item_copyright', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('published_year', models.CharField(max_length=200, null=True)),
                ('resource_url', models.CharField(max_length=200)),
                ('cover', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Genre'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='unique user rating'),
        ),
    ]
